### ISSUE TITLE
Non-interactive `new-mnemonic` command

### ISSUE THREAD

**Issue by mkykadir** [ethereum/staking-deposit-cli#268]
`new-mnemonic` command checks if the user is noted their mnemonics by prompting for mnemonics again. All prompts can be passed by providing CLI arguments to the command except for this and I think it should have completely non-interactive way of creating new mnemonic.

**Comment by Deniseget** [comment]
> `new-mnemonic` command checks if the user is noted their mnemonics by prompting for mnemonics again. All prompts can be passed by providing CLI arguments to the command except for this and I think it should have completely non-interactive way of creating new mnemonic.

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/

**Comment by pablomendezroyo** [comment]
Any progress on this?

This feature would allow automating and improving UIX in other applications

**Comment by bert2002** [comment]
I would love to see this feature as well to fully automate the creation.
