### ISSUE TITLE
Staking broken.

### ISSUE THREAD

**Issue by jack-crypto-id** [ethereum/staking-deposit-cli#296]
I am having problems with the staking program mining machine.  please help me @vellocapital007

**Comment by Vellocapital007** [comment]
The steps I gave yesterday have they been implemented?

**Comment by jack-crypto-id** [comment]
I have done it.  I post 2.5% of LP.  then what should i do next?

**Comment by Vellocapital007** [comment]
> I have done it. I post 2.5% of LP. then what should i do next?

continue your post in the next day minimum from the server.  do it until your bonus is actually distributed to the wallet normally

**Comment by jack-crypto-id** [comment]
Anything else?

**Comment by Vellocapital007** [comment]
> Anything else?

no, you only need to post a minimum of every 3 days in a row, 7 days once, 15 days and 30 days once

**Comment by Vellocapital007** [comment]
your problem is exactly the same as my coin problem in 2015. my coin name is CILKROAD

**Comment by Vellocapital007** [comment]
and now my staking program is no longer a problem thanks to these steps.  now that I have my own server, I don't have any problems related to the bonus from the blockchain server.

**Comment by Vellocapital007** [comment]
be patient and prepare your own server machine slowly.  for the above case, try to find a partner who wants to be invited to join to post on your staking project.

**Comment by jack-crypto-id** [comment]
thanks bro for the your solution.

**Comment by jack-crypto-id** [comment]
> your problem is exactly the same as my coin problem in 2015. my coin name is CILKROAD

what day does the bonus come out guys?

**Comment by Vellocapital007** [comment]
> > your problem is exactly the same as my coin problem in 2015. my coin name is CILKROAD
> 
> what day does the bonus come out guys?

after 3 consecutive days of posting then the bonus runs normally
