### ISSUE TITLE
Last three issues below this one seem to be spam

### ISSUE THREAD

**Issue by PizBernina** [ethereum/staking-deposit-cli#300]
Hi team, the issues below seem to be spam? Did not want to tag them in this one.
![image](https://user-images.githubusercontent.com/47326745/197766787-125c6929-744c-4b14-b347-ee211c6abfb2.png)

**Comment by CarlBeek** [comment]
Thanks for the report @PizBernina 🙏. Locked and closed #296, #297, & #298
