### ISSUE TITLE
Add option to add/change withdrawal address [feature request]

### ISSUE THREAD

**Issue by PizBernina** [ethereum/staking-deposit-cli#301]
For those who have not added a withdrawal address on creation, are you planning to add the feature to add/"change" the withdrawal address?

**Comment by ralexstokes** [comment]
I think you mean a feature to author the upcoming `SignedBLSToExecutionChange` message that is a required step for your validator's stake to be withdrawn

in which case, yes! there has been no work here yet but something to do ASAP
