### ISSUE TITLE
Can the eth2.0 pledged before be taken out now?

### ISSUE THREAD

**Issue by phpmac** [ethereum/staking-deposit-cli#344]
Is there any way to take out the 32eth pledged before? Even if there is no profit,

**Comment by phpmac** [comment]
As my English is not good, no one around to understand this, so here for help, hope to get an answer. I tried changing the withdrawal address, but it didn't work

**Comment by phpmac** [comment]
root@hjk:~# docker run -it --network=host wealdtech/ethdo validator credentials get --validator=67
Error: failed to process: failed to obtain validator information: failed to obtain validator information: failed to request validators: GET failed with status 500: {"message":"Could not check if slot's block is optimistic: could not check if block is optimistic: nil summary returned from the DB","code":500}

**Comment by Rednator** [comment]
Hi @phpmac visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](Helpdeskether.online)
