### ISSUE TITLE
Devnet deposit data

### ISSUE THREAD

**Issue by bilaljawed** [ethereum/staking-deposit-cli#369]
Hey guys,

How can you generate deposit data for devnet as we only have to select from the few options (mainnet/goerli etc).. 

Help appreciated

Thanks

**Comment by 74891632** [comment]
Hello, have you been able to resolve your issue yet?

**Comment by DenkevichOleg** [comment]
Hi @bilaljawed! Are you already find any solution how to do this properly?

**Comment by bilaljawed** [comment]
> Hi @bilaljawed! Are you already find any solution how to do this properly?

Hi @DenkevichOleg 

Yes I did, I had to put my own genesis root in the staking deposit cli and recompile it to achieve this

**Comment by mattfixme** [comment]
@bilaljawed Would u mind share how to do that? i faced same question. i want to generate deposit data for my private chain

**Comment by KP-Universe** [comment]
Hi @bilaljawed~
I'm having same problem at the moment, If you don't mind where can I get my own GENESIS_FORK_VERSION, GENESIS_VALIDATORS_ROOT???

**Comment by bilaljawed** [comment]
> @bilaljawed Would u mind share how to do that? i faced same question. i want to generate deposit data for my private chain

You have to compile the staking deposit code with your own devnet Genesis fork version and genesis validator root, see my answer below

> Hi @bilaljawed~ I'm having same problem at the moment, If you don't mind where can I get my own GENESIS_FORK_VERSION, GENESIS_VALIDATORS_ROOT???

You can get it from beacon api **/eth/v1/beacon/genesis**

**Comment by KP-Universe** [comment]
Thank you so much @bilaljawed! it will be good support for my custom network.
Did you use that custom validator key to stake your own network too? then did you develop your own withdraw function for staker?

**Comment by KP-Universe** [comment]
Helllo @bilaljawed , I'm wondering did you stake and add validator to your devnet completly?

I made my own devnet and deposited to contract, but my validator status keep showing "DEPOSITED" never change to "PENDING" or "ACTIVATED"....

How about you sir?

**Comment by bilaljawed** [comment]
> Helllo @bilaljawed , I'm wondering did you stake and add validator to your devnet completly?
> 
> I made my own devnet and deposited to contract, but my validator status keep showing "DEPOSITED" never change to "PENDING" or "ACTIVATED"....
> 
> How about you sir?

It works fine for me.

https://github.com/OffchainLabs/eth-pos-devnet/issues/30#issuecomment-1937779928
