### ISSUE TITLE
Generate staking data for private PoS networks 

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [ethereum/staking-deposit-cli#381]
Can we generate staking data for private PoS networks through this tool

the documentation doesn't tell anything, so i reckon its appropriate to ask

**Comment by ebygd** [comment]
You can with some [code modifications](https://github.com/ebygd/staking-deposit-cli-interop/commit/bd626d6ce99bc91dd9d75ea5aeb3898238a1ac9d). I played around with this recently if anyone is interested.

**Comment by ebygd** [comment]
I worked briefly on devnet deployments of nodes with Prysm and Lighthouse.

**Comment by SyedMuhamadYasir** [comment]
> I use Ethdo for this. They have a detailed guide for [changing withdrawal credentials](https://github.com/wealdtech/ethdo/blob/master/docs/changingwithdrawalcredentials.md).

i am using ethdo too :)

thanks for the discussion!
